# Generated by Django 5.2.3 on 2025-06-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_data',
            old_name='title',
            new_name='name',
        ),
    ]
